import { standardize } from "@/utils";

const TAXES = [
    "TARIFA BANCARIA",
    "TARIFA EMISSAO EXTRATO",
    "PACOTE DE SERVICOS",
    "BRAD. VIDA E PREV.",
    "CARTAO DE CREDITO ANUIDADE",
    "CARTAO CREDITO ANUIDADE",
    "SEGURO PRESTAMISTA",
    "PSERV",
    "SEGURO AP - SEGUROS UNIMED",
    "SEG UNIMED CLUBE",
    "SEBRASEG",
    "EAGLE SOCIEDADE DE CREDITO DIRETO",
    "TITULO DE CAPITALIZACAO",
    "CHUBB SEGUROS BRASIL SA",
    "LIBERTY SEGUROS S/A",
    "PORTO SEGURO CIA DE SEGUROS GERAIS",
    "SUDAMERICA CLUBE DE SERVICOS",
    "BINCLUB SERVICOS DE ADMINISTRACAO",
    "SABEMI",
    "ZURICH",
    "MBM PREVIDENCIA COMPLEMENTAR",
    "SEGURADORA SECON",
    "SERVICO CARTAO PROTEGIDO",
    "BRADESCO AUTO RE S/A",
    "BRADESCO AUTO RE",
    "BRADESCO SEG-RESID/OUTROS",
    "FINANCOB INTERMEDIACAO DE NEGOCI",
    "ASENAS ASSOCIACAO DOS SERVIDORES",
    "BRADESCO VIDA E PREVIDENCIA",
    "ODONTOPREV",
    "MORA"
].map(standardize)

const COLLAPSED_TAXES = [
    "TARIFA BANCARIA",
    "TARIFA EMISSAO EXTRATO",
    "PACOTE DE SERVICOS",
].map(standardize)

const ADHOC_TAXES = [
    "PAGTO ELETRON COBRANCA",
    "DEBITO AUTOMATICO",
].map(standardize)

export {
    TAXES,
    COLLAPSED_TAXES,
    ADHOC_TAXES
}